# This workflow will build a package using Maven 
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Publish Release

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  LATEST: 1.5.3

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['1.5.0', '1.5.1', '1.5.2', '1.5.3']

    permissions:
      contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven

    - name: Prepare Release
      run: ./scripts/prepare-build.sh
      env:
        GUACAMOLE_VERSION: ${{ matrix.version }}

    - name: Build with Maven
      run: mvn -B package -Djar.finalName=guacamole-${{ matrix.version }}-auth-jwt-${{ github.ref_name}} --file pom.xml

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.ref_name }}-${{ matrix.version }}
        path: target/*.jar

  docker:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read
      packages: write

    steps:
    - name: Download Lastest Artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ github.ref_name}}-${{ env.LATEST }}
        path: target

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        flavor: |
          suffix=-guac${{ env.LATEST }}

    - name: Build Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}